name: Deploy Backend (Lambda)

on:
  push:
    branches: [ main ]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build Lambda zip (single-folder layout)
        working-directory: backend
        run: |
          rm -rf build && mkdir -p build
          pip install -r requirements.txt -t build
          cp -R . build/
          cd build
          zip -r ../function.zip .
          cd ..

      # (Optional) set/update environment vars from GitHub Secrets
      # - name: Update Lambda env vars
      #   run: |
      #     aws lambda update-function-configuration \
      #       --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
      #       --environment "Variables={GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GEMINI_MODEL=${{ secrets.GEMINI_MODEL }},FRONTEND_ORIGINS='${{ secrets.FRONTEND_ORIGINS }}'}"

      - name: Update Lambda code
        working-directory: backend
        run: |
          aws lambda update-function-code \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --zip-file "fileb://function.zip"

      - name: Publish Lambda version (optional)
        run: |
          aws lambda publish-version --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}"
