name: Deploy Frontend (S3 + CloudFront)

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Create .env.production for Vite
        working-directory: frontend
        run: |
          echo "VITE_API_BASE=${{ secrets.API_BASE_URL }}" > .env.production

      - name: Install & Build
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Sync to S3
        run: |
          aws s3 sync frontend/dist "s3://${{ secrets.S3_BUCKET }}" \
            --delete \
            --cache-control "public,max-age=31536000,immutable" \
            --exclude "index.html"
          aws s3 cp frontend/dist/index.html "s3://${{ secrets.S3_BUCKET }}/index.html" \
            --cache-control "no-cache,no-store,must-revalidate"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id "${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}" \
            --paths "/*"
